// backend/src/types/websocket.types.ts
// All WebSocket message types for the streaming agent protocol.
//
// PROTOCOL DESIGN:
// Every message is a typed JSON object with a "type" discriminant.
// This makes it easy to switch on the type on both sides.
//
// MESSAGE FLOW FOR ONE AGENT SESSION:
//   CLIENT → SERVER: { type: "start", query, sessionId }
//   SERVER → CLIENT: { type: "connected", sessionId }
//   SERVER → CLIENT: { type: "status", status: "thinking" }
//   SERVER → CLIENT: { type: "status", status: "searching" }
//   SERVER → CLIENT: { type: "step", step: { ... } }
//   SERVER → CLIENT: { type: "quality", score: 0.45, shouldRetry: true }
//   SERVER → CLIENT: { type: "status", status: "generating" }
//   SERVER → CLIENT: { type: "complete", result: { ... } }
//   SERVER → CLIENT: { type: "error", message: "..." }   (on failure)

import type { AgentStatus, AgentStep, AgentResult } from "./agent.types"

// ── Messages the CLIENT sends to the SERVER ───────────────────────────────

export type ClientMessage = StartAgentMessage | PingMessage | AuthMessage

export interface StartAgentMessage {
  type: "start"
  query: string
  sessionId: string // generated by the client
}

export interface PingMessage {
  type: "ping"
}

export interface AuthMessage {
  type: "auth"
  token: string
}

// ── Messages the SERVER sends to the CLIENT ───────────────────────────────

export type ServerMessage =
  | ConnectedMessage
  | AuthConfirmedMessage
  | AgentStatusMessage
  | AgentStepMessage
  | QualityCheckMessage
  | AgentCompleteMessage
  | AgentErrorMessage
  | PongMessage

export interface ConnectedMessage {
  type: "connected"
  sessionId: string
  message: string
}

export interface AuthConfirmedMessage {
  type: "auth_confirmed"
  userId: string
}

export interface AgentStatusMessage {
  type: "status"
  status: AgentStatus
  sessionId: string
  message: string // human-readable description of current stage
}

export interface AgentStepMessage {
  type: "step"
  sessionId: string
  step: AgentStep
}

export interface QualityCheckMessage {
  type: "quality"
  sessionId: string
  score: number // 0-1 overall quality score
  shouldRetry: boolean
  retryReason?: string
  suggestedQuery?: string
}

export interface AgentCompleteMessage {
  type: "complete"
  sessionId: string
  result: AgentResult
}

export interface AgentErrorMessage {
  type: "error"
  sessionId: string
  message: string
  code?: string
}

export interface PongMessage {
  type: "pong"
}

// ── Helper: type-safe message serialiser ─────────────────────────────────
export function toJson(message: ServerMessage): string {
  return JSON.stringify(message)
}

// ── Helper: type-safe message parser ─────────────────────────────────────
export function parseClientMessage(raw: string): ClientMessage | null {
  try {
    const parsed = JSON.parse(raw) as { type?: unknown }

    if (typeof parsed.type !== "string") return null

    switch (parsed.type) {
      case "start":
      case "ping":
      case "auth":
        return parsed as ClientMessage
      default:
        return null
    }
  } catch {
    return null
  }
}
